spring:
  application:
    name: library-tracking-service
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8081
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
eureka:
  client:
    serviceUrl:
      defaultZone: http://library-eureka-discovery-service:8761/eureka/
