management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, gateway

spring:
  application:
    name: library-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://library-eureka-discovery-service:8761/eureka